---
- hosts: 192.168.132.152
  user: root
  sudo: yes
  tasks: 
    - name: installing httpd package
      yum: name=httpd state=installed
    notify: restart httpd server
  handlers:
    - name: restart httpd server
      service: name=httpd state=restarted
